version: '3.7'
services:
  cals-test:
    build: 
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV:-test}
      NODE_ENV: test
      CALS_API_URL: "https://calsapi.preint.cwds.io"
      GEO_SERVICE_URL: "https://geo.preint.cwds.io"
      AUTHENTICATION_API_BASE_URL: "https://web.preint.cwds.io/perry"
      BASE_SEARCH_API_URL: "https://dora.preint.cwds.io"
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    links:
      - redis
    tty: true
    stdin_open: true
  redis:
    image: 'redis:3.0'
    ports:
      - "6379:6379"
